GET http://localhost:8080/v1/organization/optimaGrowth/license/1234
Content-Type: application/json

###
POST http://localhost:8082/v1/organization/1234/license
Content-Type: application/json
Accept: application/json

{
  "licenseId": "1234",
  "organizationId": "optimaGrowth",
  "description": "설명",
  "productName": "제품",
  "licenseType": "일반"
}

###
GET http://localhost:8070/eureka/apps/organization-service
Content-Type: application/json
Accept: application/json